#
# © ОАО «Северное ПКБ», 2013
#
---
# add new node in existed glusterfs volume
    - name: добавление узлов в glusterfs
      command: gluster peer probe {{ item }}
      with_items:
         groups.new_nodes
      any_errors_fatal: true

    - name: добавление нового узла в том
      command: gluster volume add-brick {{ gluster.volume }} {{ item }}:{{ gluster.placedir }}
      with_items:
         groups.new_nodes
      any_errors_fatal: true

    - name: запуска ребалансировки тома
      command: gluster volume rebalance {{ gluster.volume }} start
      register: result
      failed_when: "'nothing to rebalance ' not in result.stdout and result.rc != 0"

