# vars for corosync and pacemaker

corosync:
  # 226.95.1.1, 226.94.1.1
  mcastaddr: 239.255.1.1
  # 4000
  mcastport: 4001

resource_id:
   ald_client: 'ald_clientside'
   ald_server: 'ald_server'

cluster_fs:
   # Допустимые значения
   # 0(проверка, что том смонтирован)
   # 10(проверка, что позволяется операция чтения данных с тома)
   # 20(проверка, что позволяется операция записи данных на том)
   check_level: 0
   # Допустимые значения смотрите в документации Pacemaker (5.7.1. Monitoring Resources for Failure)
   on_fail_operation: 'stop'

