#
# © ОАО «Северное ПКБ», 2014
#
---
# полное удаление ПК КВГ с узлов из группы [nodes]
# если необходимо удалить один из узлов следует использовать remove_cluster_nodes
# предварительно заполнить группу [remove_nodes] в файле stage

    - name: Останавливаем работающие сервисы corosync и pacemaker
      command: killall -s 9 {{ item }}
      with_items: [cib, stonithd, lrmd, attrd, pengine, crmd, mgmtd, corosync]
      ignore_errors: true
      tags: [ pacemaker ]

    - name: удаление pacemaker и сorosync
      apt: pkg={{ item }} purge=yes state=absent
      with_items: 
        - pacemaker-mgmt
        - pacemaker-mgmt-client
        - pacemaker 
        - corosync
        - resource-agents
        - libstonithd1
        - libcrmcommon2
        - cluster-glue
      tags: [ pacemaker ]

    - name: удаление базы cib
      command: rm -rf /var/lib/heartbeat
      tags: [ pacemaker ]

    - name: продолжить удаление пакетов (будут удалены пакет ALD, ПК Виртуализации и ПК управления)?
      pause: prompt="press any key for continue or ctrl+c for cancel" seconds=60

    - name: удаление пакетов ALD
      apt: pkg={{ item }} purge=yes state=absent
      with_items:
       - smc-ald-audit
       - smc-ald-capabilities
       - smc-ald-device-ctrl
       - smc-ald-hosts
       - smc-ald-mac
       - smc-ald-policies
       - smc-ald-services
       - smc-ald-tasks
       - smc-ald-users
       - smolensk-security-ald
       - ald-client-fs
       - ald-admin-common
       - ald-admin-parsec-aud
       - ald-admin-parsec-devac
       - ald-client-common
       - ald-admin
       - ald-admin-parsec-mac
       - ald-server
       - ald-server-common
       - slapd
       - haveged
      tags: [ ald ]

    - name: SIGKILL для всеx VM
      command: killall -s 9 kvm
      ignore_errors: true
      tags: [libvirt]

    - name: удаление определений VM
      shell: virsh list --inactive --name | cut -d " " -f 4 | xargs -n 1 virsh undefine
      ignore_errors: true
      tags: [libvirt]

    - name: удаление пакетов ПК Виртуализации
      apt: pkg={{ item }} purge=yes state=absent
      with_items: [libvirt-bin, virtinst, qemu-kvm]
      tags: [libvirt]

    - name: удаление пакетов ПК Управления
      apt: pkg={{ item }} purge=yes state=absent
      with_items:
       - firefox
       - python-django
       - python-setuptools
       - apache2
       - libapache2-mod-wsgi
       - libapache2-mod-auth-kerb
       - python-netsnmp
       - ipmitool
       - hac-control-apache
       - hac-control
       - python-django-hac
       - python-hac-tools
       - xrdp
      tags: [hac_cntrl]

    - name: закрываем процессы ALD
      shell: killall -s 9 {{ item }}
      with_items: ald.services_list
      ignore_errors: true
      tags: [ ald ]

    - name: продолжить удаление пакетов (будут удалены пакеты и компоненты ПК РФС) ?
      pause: prompt="press any key for continue or ctrl+c for cancel"  seconds=60

    - name: отмонтирование glusterfs
      shell: umount {{ gluster.mount_point }}
      ignore_errors: true
      tags: [ gluster ]

    - name: удаление пакетов glusterfs
      apt: pkg={{ item }} purge=yes state=absent
      with_items: [glusterfs-server, glusterfs-client, glusterfs-common]
      tags: [ gluster ]

    - name: ожидание остановки glusterfs
      pause: seconds=5
      tags: [ gluster ]

    - name: killall glusterfs
      shell: killall -s 9 {{ item }}
      with_items: [glusterfsd, glusterfs, glusterd]
      ignore_errors: true
      tags: [ gluster ]

    - name: удаление точки монтирования gluster
      shell: rm -rf {{ gluster.mount_point }}
      tags: [ gluster ]

    - name: удаление содержимого glusterfs разделов
      shell: rm -rf /srv/*
      tags: [ gluster ]

    - name: удаление конфигурации glusterd
      command: rm -rf /etc/glusterd removes=/etc/glusterd
      tags: [ gluster ]

    - name: удаление конфигурации glusterd
      command: rm -rf /var/lib/glusterd removes=/var/lib/glusterd
      tags: [ gluster ]

    - name: удаление конфигурации glusterfs
      command: rm -rf /etc/glusterfs removes=/etc/glusterfs
      tags: [ gluster ]

    - name: удаление лог файлов из /var/log/glusterfs
      shell: rm -rf /var/log/glusterfs/*
      tags: [ gluster ]

    - name: перезагружаем узлы
      command: /sbin/reboot -t now
      tags: [reboot]

