#
# © ОАО «Северное ПКБ», 2014
#
---
# full uninstall HA cluster

    - name: Останавливаем работающие сервисы corosync и pacemaker
      command: killall -s 9 {{ item }}
      with_items: [cib, stonithd, lrmd, attrd, pengine, crmd, mgmtd, corosync]
      ignore_errors: true
      tags: [ pacemaker ]

    - name: удаление pacemaker и сorosync
      apt: pkg={{ item }} purge=yes state=absent
      with_items: [pacemaker-mgmt, pacemaker-mgmt-client, pacemaker, corosync]
      tags: [ pacemaker ]
      
    - name: удаление базы cib
      command: rm -rf /var/lib/heartbeat
      tags: [ pacemaker ]  
      
    - name: продолжить удаление пакетов (будут удалены пакет ALD, ПК Виртуализации и ПК управления)?
      pause: prompt="press any key for continue or ctrl+c for cancel"  
      
    - name: удаление пакетов ALD
      apt: pkg={{ item }} purge=yes state=absent
      with_items:
       - smc-ald-audit
       - smc-ald-capabilities
       - smc-ald-device-ctrl
       - smc-ald-hosts
       - smc-ald-mac
       - smc-ald-policies
       - smc-ald-services
       - smc-ald-tasks
       - smc-ald-users
       - smolensk-security-ald
       - ald-client-fs
       - ald-admin-common
       - ald-admin-parsec-aud
       - ald-admin-parsec-devac
       - ald-client-common
       - ald-admin
       - ald-admin-parsec-mac
       - ald-server
       - ald-server-common
       - slapd
       - haveged
      tags: [ ald ]

    - name: удаление пакетов ПК Виртуализации
      apt: pkg={{ item }} purge=yes state=absent
      with_items: [libvirt-bin, virtinst]
      tags: [libvirt]

    - name: удаление пакетов ПК Управления
      apt: pkg={{ item }} purge=yes state=absent
      with_items:
       - firefox
       - python-django
       - python-setuptools
       - apache2
       - libapache2-mod-wsgi
       - libapache2-mod-auth-kerb
       - python-netsnmp
       - ipmitool
       - hac-control-apache
       - hac-control
       - python-django-hac
       - python-hac-tools
      tags: [hac_cntrl]

    - name: закрываем процессы ALD
      shell: killall -s 9 {{ item }}
      with_items: services_list
      ignore_errors: true
      tags: [ ald ]

    - name: продолжить удаление пакетов (будут удалены пакеты и компоненты ПК РФС)?
      pause: prompt="press any key for continue or ctrl+c for cancel"

    - name: удаление пакетов glusterfs
      apt: pkg=glusterfs-server purge=yes state=absent
      tags: [ gluster ]

    - name: удаление содержимого glusterfs разделов
      shell: rm -rf /srv/*
      tags: [ gluster ]

    - name: удаление конфигурации glusterd
      command: rm -rf /etc/glusterd removes=/etc/glusterd
      tags: [ gluster ]

    - name: удаление конфигурации glusterfs
      command: rm -rf /etc/glusterfs removes=/etc/glusterfs
      tags: [ gluster ]

    - name: перезагружаем узлы
      command: /sbin/reboot -t now
      tags: [ pacemaker, gluster ]

