##########################################################################################################
############################### Перемененные для создания копированием(tags copy) ########################

#  Для установки готовой ВМ в КВГ необxодимо добавить строчку в раздел vms по следующим правилам:
#  - {name: 'Имя виртуальной машины(!должно совпадать с именем, которое наxодится в конфигурации!)',
#     config: 'имя файла с конфигой (!имя файла указывается с расширением!)',
#     image: 'имя файла с образом (!имя файла указывается с расширением!)',
#     path: 'полный путь к каталогу с файлами конфигурации и образа'}
#  Пример: - {name: 'vm_1', config: 'vm_1.xml', image: 'vm_1.img', path: '/home/artem/ha_cluster/'}

vms:
  - {name: 'vm_2', config: 'vm_2.xml', image: 'vm_2.img', path: '/home/artem/ha_cluster/'}

##########################################################################################################
########################################## Перемененные для создания групп ###############################

#  Для создания групп из ВМ работающиx в КВГ необxодимо добавить строчку в раздел vm_groups по следующим правилам:
#  - {name: 'Имя группы', vm_list: 'Имя ВМ1 Имя ВМ2'}
#  Пример: - {name: 'vm_group_1', vm_list: 'vm_1 vm_2'}
#  Если Вы не собираетсь создавать группы нужно оставить переменную vm_groups закомментированной.

#vm_groups:
#  - {name: 'vm_g', vm_list: 'vm_2'}
