#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: установка пакета haproxy
      apt: pkg=haproxy state=latest force=yes
      when: inventory_hostname in groups.admin_stations

    - name: настройка haproxy
      template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
      when: inventory_hostname in groups.admin_stations

    - name: включение haproxy
      lineinfile: dest=/etc/default/haproxy
                  regexp='^ENABLED'
                  line='ENABLED=1'
                  state=present
      when: inventory_hostname in groups.admin_stations

    - name: запуск демона haproxy
      service: name=haproxy state=restarted enabled=yes
      when: inventory_hostname in groups.admin_stations
