#
# © ОАО «Северное ПКБ», 2013-2014
#
---
    - name: создание каталога для настроек firefox
      file: path={{ firefox.path_to_settings }} state=directory
      ignore_errors: true

    - name: настройка firefox
      template: src=firefox.js.j2 dest={{ firefox.path_to_settings }}/firefox.js
                owner=root group=root mode=0644

    - name: создание прокси vncviewer для открытия vnc-ссылок из firefox
      copy: src=vncviewer-firefox dest=/usr/bin owner=root group=root mode=0777

    - name: создание прокси xfreerdp для открытия rdp-ссылок из firefox
      copy: src=xfreerdp-firefox dest=/usr/bin owner=root group=root mode=0777

    - name: создание прокси spicy-gtk-client для открытия vnc-ссылок из firefox
      copy: src=spicy-firefox dest=/usr/bin owner=root group=root mode=0777

    - name: настройка профиля policykit для spice
      copy: src=org.spice-space.lowlevelusbaccess.policy
            dest=/usr/share/polkit-1/actions/
            owner=root group=root

    - name: создание каталогов для профилей firefox
      file: path={{ dirs.ald_env_users }}/{{ ald.users.admin.login }}/.mozilla/firefox/{{ ald.users.admin.login }}.default
            state=directory owner={{ ald.users.admin.login }} group={{ ald.users.admin.group }}
      ignore_errors: true
      when: inventory_hostname in groups.admin_stations

    - name: создание профиля пользователя
      template: src=profiles.ini.j2
                dest={{ dirs.ald_env_users }}/{{ ald.users.admin.login }}/.mozilla/firefox/profiles.ini
                owner={{ ald.users.admin.login }} group={{ ald.users.admin.group }}
      when: inventory_hostname in groups.admin_stations

    - name: создание mimeTypes в профиле пользователя firefox
      copy: src=mimeTypes.rdf
            dest={{ dirs.ald_env_users }}/{{ ald.users.admin.login }}/.mozilla/firefox/{{ ald.users.admin.login }}.default/
            owner={{ ald.users.admin.login }} group={{ ald.users.admin.group }}
      when: inventory_hostname in groups.admin_stations


