#
# © ОАО «Северное ПКБ», 2013-2014
#
---
    - name: создание каталога для настроек firefox
      file: path={{ firefox.path_to_settings }} state=directory
      ignore_errors: True

    - name: настройка firefox
      template: src=firefox.js.j2 dest={{ firefox.path_to_settings }}/firefox.js owner=root group=root mode=0644

    - name: создание прокси vncviewer для открытия vnc-ссылок из firefox
      copy: src=vncviewer-firefox dest=/usr/bin owner=root group=root mode=0777
