#
# © ОАО «Северное ПКБ», 2013
#
---
# setup main settings of libvirt

    - name: создание libvirt.conf и qemu.conf
      copy: src={{ item }} dest=/etc/libvirt owner=root group=root mode=0644
      with_items: ['libvirtd.conf', 'qemu.conf']

    - name: открытие TCP порта
      lineinfile: dest=/etc/default/libvirt-bin
                  line="libvirtd_opts=\"-d -l\""
                  regexp="^libvirtd_opts="
                  state=present

    - name: включение загрузки библиотеки для O_DIRECT
      lineinfile: dest=/etc/default/libvirt-bin
                  line="export LD_PRELOAD=/lib/liboindirect.so"
                  regexp="^export LD_PRELOAD="
                  state=present
      notify: restart libvirt-bin

    - name: создание каталога для ВМ (образы и файлы конфигурации)
      file: path={{ dirs.vm_images }} state=directory
      register: create_vm_images
      when: inventory_hostname == common.master_node
      ignore_errors: true

    - name: перемещение файлов /etc/libvirt/qemu на glusterfs
      command: mv -f /etc/libvirt/qemu {{ dirs.vm_images }}
      when: create_vm_images.changed and inventory_hostname == common.master_node

    - name: делаем ссылку qemu в /etc/libvirt/
      file: src={{ dirs.vm_images }}/qemu dest=/etc/libvirt/qemu state=link
      when: create_vm_images.changed and inventory_hostname == common.master_node
