#
# © ОАО «Северное ПКБ», 2013
#
---
# setup main settings of libvirt
    - name: создание libvirt.conf
      copy: src={{ item }} dest=/etc/libvirt owner=root group=root mode=0644
      with_items: ['libvirtd.conf', 'qemu.conf']

    - name: открытие TCP порта
      lineinfile: dest=/etc/default/libvirt-bin
                  line="libvirtd_opts=\"-d -l\""
                  regexp="^libvirtd_opts="
                  state=present

    - name: включение загрузки библиотеки для O_DIRECT
      lineinfile: dest=/etc/default/libvirt-bin
                  line="export LD_PRELOAD=/lib/liboindirect.so"
                  regexp="^export LD_PRELOAD="
                  state=present
      notify: restart libvirt-bin

    - name: отмонтирование glusterfs
      command: umount {{ gluster.mount_point }}
      ignore_errors: true

    - name: перезапуск службы glusterfs-server
      service: name=glusterfs-server state=restarted

    - name: ожидание перезапуска демон glusterfs
      pause: seconds=10

    - name: монтирование glusterfs
      command: mount.glusterfs {{ common.master_node }}:/{{ gluster.volume }} {{ gluster.mount_point }}
      when: inventory_hostname == common.master_node

    - name: создание каталога для ВМ (образы)
      file: path={{ dirs.vm_images }} state=directory mode=0777
      when: inventory_hostname == common.master_node
      ignore_errors: true

    - name: создание каталога для ВМ (файлы конфигурации)
      file: path={{ dirs.vm_images }}/qemu  state=directory mode=0777
      when: inventory_hostname == common.master_node
      ignore_errors: true

    - name: отмонтирование glusterfs
      command: umount {{ gluster.mount_point }}
      when: inventory_hostname == common.master_node

