#
# © ОАО «Северное ПКБ», 2014
#
--- 
- name: копирование файлов настроек для ALD
  copy: src=ald-conf/{{ ald.master_ald_srv }}${item} dest=${item} backup=yes 
  with_items: ald_files

- name: удаление исходной схемы LDAP
  file: path=/etc/ldap/slapd.d state=absent

- name: копирование файлов схемы LDAP
  copy: src=ald-conf/{{ ald.master_ald_srv }}/etc/ldap/slapd.d dest=/etc/ldap
        owner=openldap group=openldap

- name: установка прав на подкаталоги схемы
  file: path=/etc/ldap/${item} state=directory
          owner=openldap group=openldap mode=0750
  with_items:
    - slapd.d
    - slapd.d/cn=config
    - slapd.d/cn=config/cn=schema
    - slapd.d/cn=config/olcDatabase={2}hdb

- name: установка прав на файл ключа
  file: path=/etc/ldap/slapd.keytab state=file
        owner=openldap group=openldap mode=0400

- name: замена неверного файла /etc/init.d/nscd
  copy: src=nscd dest=/etc/init.d/nscd owner=root group=root mode=0755

- name: удаление старой базы LDAP
  command: rm -rf /var/lib/ldap removes=/var/lib/ldap

- name: подмена каталога /var/lib/ldap
  file: src={{ gluster.mount_point }}/ldap dest=/var/lib/ldap state=link

- name: удаление старой базы Kerberos
  command: rm -rf /var/lib/krb5kdc removes=/var/lib/krb5kdc

- name: подмена каталога /var/lib/krb5kdc
  file: src={{ gluster.mount_point }}/krb5kdc dest=/var/lib/krb5kdc state=link