#
# © ОАО «Северное ПКБ», 2014
#
---
- name: удаление подмены имени для aldcd
  lineinfile: dest=/etc/default/aldcd
              regexp='^export LD_PRELOAD'
              state=absent
  tags: [ config ]

