#
# © ОАО «Северное ПКБ», 2014
#
---
- name: остановка сервиса OpenLDAP
  service: name=slapd state=stopped

- name: удаление старого keytab
  file: path=/etc/ldap/slapd.keytab state=absent

- name: добавление принципала ldap
  command: kadmin.local -q 'ktadd -k /etc/ldap/slapd.keytab -norandkey ldap/{{ ald.master_node }}.{{ ald.domain }}'

- name: установка прав на keytab
  file: path=/etc/ldap/slapd.keytab state=file owner=openldap group=openldap

- name: создание каталога LDAP на общем хранилище
  file: path={{ gluster.mount_point }}/ldap state=directory
        owner=openldap group=openldap mode=0700
  when: inventory_hostname == common.master_node

- name: перенос на Gluster базы LDAP
  command: cp -pfR /var/lib/ldap {{ gluster.mount_point }}
  when: inventory_hostname == common.master_node

#- name: удаление старой базы LDAP
#  command: rm -rf /var/lib/ldap removes=/var/lib/ldap

- name: подмена каталога /var/lib/ldap
  command: mount --bind -o _netdev {{ gluster.mount_point }}/ldap /var/lib/ldap
#  mount: name=/var/lib/ldap src={{ gluster.mount_point }}/ldap
#         fstype=none opts=bind state=mounted
#  file: src={{ gluster.mount_point }}/ldap dest=/var/lib/ldap state=link
#        owner=openldap group=openldap

#- name: установка прав на /var/lib/ldap
#  file: path=/var/lib/ldap state=directory
#        owner=openldap group=openldap

- name: запуск сервиса OpenLDAP
  service: name=slapd state=started
  when: inventory_hostname == common.master_node

