#
# © ОАО «Северное ПКБ», 2014
#
---   
- include: server.yml tags=ald-server
  when: inventory_hostname in groups.nodes

- include: client.yml tags=ald-client

- service: name={{ item }} enabled=no
  with_items: ald.services_list
  when: inventory_hostname in groups.nodes
  ignore_errors: yes

- service: name={{ item }} state=stopped
  with_items: ald.services_list  
  when: inventory_hostname in groups.nodes
  ignore_errors: yes