#
# © ОАО «Северное ПКБ», 2014
#
---
- include: common.yml

- include: server.yml

- include: kerberos.yml

- include: openldap.yml

- include: ald.yml

- include: ald-master.yml
  when: inventory_hostname == common.master_node

#- include: ald-slave.yml tags=ald-slave
#  when: inventory_hostname != common.master_node

- name: создание каталога apache
  file: path=/etc/apache2 state=directory

- name: копирование keytab для apache
  copy: src=krb.keytab dest=/etc/apache2/krb.keytab mode=0644 owner=www-data group=www-data

- name: удаление временных файлов
  local_action: command rm -rf ald-conf

- service: name={{ item }} enabled=no
  with_items: ald.services_list

