#
# © ОАО «Северное ПКБ», 2014
#
---     
- name: установка haveged
  apt: pkg=haveged state=latest
  #when: setup.haveged
  tags: [ packages ]

- name: установка ald пакетов
  apt: pkg=$item state=latest
  with_items:
    - ald-admin-common
    - ald-server-common
    - ald-client-common    
    - ald-server-dc
  tags: [ packages ]
  
- name: создание файла настройки пользователей
  template: src=pass-file.j2 dest=/root/pass-file mode=0600
  tags: [ pass-file ]
  
- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ]

- name: настройка ALD сервера
  ald: task=init_server pass_file=/root/pass-file
  when: inventory_hostname == ald.master_ald_srv
  
- name: Make keytab for admin/admin
  command: kadmin.local -q 'ktadd -k /root/admin.keytab -norandkey admin/admin'  
  when: inventory_hostname == ald.master_ald_srv

- name: создание группы administrators в ALD
  ald: task=group group=administrators pass_file=/root/pass-file
  when: inventory_hostname == ald.master_ald_srv

- name: создание группы users в ALD
  ald: task=group group=users pass_file=/root/pass-file
  when: inventory_hostname == ald.master_ald_srv
  
- name: создание пользователя kvg_admin в ALD
  ald: task=user user=kvg_admin pass_file=/root/pass-file    
  when: inventory_hostname == ald.master_ald_srv
    

- name: Добавление пользователя в группу administrators
  command: ald-admin group-mod administrators -f --pass-file=/root/pass-file --add-users --user=kvg_admin           
  when: inventory_hostname == ald.master_ald_srv
   
- name: установка модулей ALD для панели SMC
  apt: pkg=$item state=latest
  with_items:
      - smc-ald-audit
      - smc-ald-capabilities
      - smc-ald-device-ctrl
      - smc-ald-hosts
      - smc-ald-mac
      - smc-ald-policies
      - smc-ald-services
      - smc-ald-tasks
      - smc-ald-users
  tags: [ packages ]
    
- name: настройка резервного сервера ALD
  command: ald-client slavesrv-init -f --pass-file=/root/pass-file
  when: inventory_hostname == ald.slave_ald_srv
  