#
# © ОАО «Северное ПКБ», 2014
#
---
- name: установка haveged
  apt: pkg=haveged state=latest
  tags: [ packages ]

- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ]

#- name: backup /etc/hosts
#  fetch: src=/etc/hosts dest=roles/ald_setup/files/hosts_{{ inventory_hostname }} validate_md5=yes flat=yes fail_on_missing=yes

- name: настройка /etc/hosts
  template: src=hosts_ald.j2 dest=/etc/hosts

- name: замена скрипта запуска OpenLDAP
  copy: src=slapd.orig dest=/etc/init.d/slapd owner=root group=root mode=0755

- name: настройка ALD сервера
  command: ald-init init -f --pass-file=/root/pass-file
  environment: virthostname_env

- name: Make keytab for admin/admin
  command: kadmin.local -q 'ktadd -k /root/admin.keytab -norandkey admin/admin'

- name: создание принципала для узлов кластера
  ald: task=host host={{ item }}.{{ ald.domain }} pass_file=/root/pass-file
  with_items: groups.nodes

- name: создание принципалов OpenLDAP
  command: ald-admin service-add ldap/{{ item }}.{{ ald.domain }} -f --pass-file=/root/pass-file
  with_items: groups.nodes

- name: остановка сервисов ALD
  service: name={{ item }} state=stopped
  with_items: [aldd, aldcd, samba, nslcd, nscd, slapd, krb5-kdc, krb5-admin-server]

- name: замена неверного файла /etc/init.d/nscd
  copy: src=nscd dest=/etc/init.d/nscd owner=root group=root mode=0755

#- name: изменение /etc/hosts
#  lineinfile: dest=/etc/hosts
#              regexp='{{ ald.master_node }}.{{ ald.domain }} ald'
#              line="{{ hostvars[common.master_node]['ansible_eth0']['ipv4']['address'] }} {{ ald.master_node }}.{{ ald.domain }} {{ ald.master_node }}"
#              state=present
#  when: inventory_hostname != common.master_node

#- name: копирование файлов настроек для LDAP
#  fetch: src=/etc/ldap/slapd.d/{{ item }} dest=ald-conf
#  with_items: ldap_files

