#
# © ОАО «Северное ПКБ», 2014
#
---
- name: установка haveged
  apt: pkg=haveged state=latest
  tags: [ packages ]

- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ]

- name: настройка /etc/hosts
  template: src=hosts_ald.j2 dest=/etc/hosts

- name: настройка ALD сервера
  command: ald-init init -f --pass-file=/root/pass-file
  environment: virthostname_env

- name: Make keytab for admin/admin
  command: kadmin.local -q 'ktadd -k /root/admin.keytab -norandkey admin/admin'

- name: создание принципала для узлов кластера
  ald: task=host host={{ item }}.{{ ald.domain }} pass_file=/root/pass-file
  with_items: groups.nodes

- name: остановка сервисов ALD
  service: name={{ item }} state=stopped
  with_items: [aldd, aldcd, samba, nslcd, nscd, slapd, krb5-kdc, krb5-admin-server]

- name: замена неверного файла /etc/init.d/nscd
  copy: src=nscd dest=/etc/init.d/nscd owner=root group=root mode=0755

