#
# © ОАО «Северное ПКБ», 2014
#
---        
- name: установка haveged
  apt: pkg=haveged state=latest  
  tags: [ packages ]

- name: установка пакетов для сервера ALD
  apt: pkg=$item state=latest
  with_items:
    - ald-server
    - ald-server-common     
  tags: [ packages ]
                
#- name: установка ald пакетов
  #apt: pkg=$item state=latest
  #with_items:
    #- ald-admin-common
    #- ald-server-common
    #- ald-client-common    
    #- ald-client-fs    
    #- ald-server-dc
    #- smolensk-security-ald
  #tags: [ packages ]
  
- name: создание файла настройки пользователей
  template: src=pass-file.j2 dest=/root/pass-file mode=0600
  tags: [ pass-file ]
  
- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ]

- name: удаление старых каталогов KRB
  command: rm -r  /var/lib/krb5kdc
  ignore_errors: yes

- name: удаление старых каталогов LDAP
  command: rm -r  /var/lib/ldap
  ignore_errors: yes

- name: настройка ALD сервера
  command: ald-init init -f --pass-file=/root/pass-file

- name: Make keytab for admin/admin
  command: kadmin.local -q 'ktadd -k /root/admin.keytab -norandkey admin/admin'    

- name: создание группы в ALD
  ald: task=group group={{ item }} pass_file=/root/pass-file
  with_items: ald.groups  
  
- name: создание пользователя администратора в ALD
  ald: task=user user={{ ald.kvg_admin_name }} pass_file=/root/pass-file      
    
- name: Добавление пользователя в группу administrators
  command: ald-admin group-mod {{ item }} -f --pass-file=/root/pass-file --add-users --user={{ ald.kvg_admin_name }}             
  with_items: ald.groups
  
- name: Добавление привелегий для пользователя
  command: ald-admin user-ald-cap {{ ald.kvg_admin_name }} -f --pass-file=/root/pass-file --c-admin=1 --c-all-hosts-add=1 --c-adm-user=1  
                                   
- include: ald-master.yml tags=ald-master
  when: inventory_hostname == ald.master_ald_srv

- include: ald-slave.yml tags=ald-slave
  when: inventory_hostname != ald.master_ald_srv

- service: name={{ item }} enabled=false
  with_items: ald.services_list
  
- service: name={{ item }} state=stopped
  with_items: ald.services_list  

- name: удаление временных файлов
  local_action: command rm -rf ald-conf