#
# © ОАО «Северное ПКБ», 2014
#
---        
- name: установка haveged
  apt: pkg=haveged state=latest  
  tags: [ packages ]

- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ]

- name: настройка ALD сервера
  command: ald-init init -f --pass-file=/root/pass-file
  environment: virthostname_env

- name: Make keytab for admin/admin
  command: kadmin.local -q 'ktadd -k /root/admin.keytab -norandkey admin/admin'    

- name: создание приципала для ПК Управления
  command: ald-admin service-add HTTP/{{ hac_cntrl.name }}.{{ ald.domain }} -f --pass-file=/root/pass-file

- name: добавление приципала для ПК Управления в группу mac
  command: ald-admin sgroup-svc-add HTTP/{{ hac_cntrl.name }}.{{ ald.domain }} --sgroup=mac --pass-file=/root/pass-file

- name: создание keytab для apache
  command: ald-client  update-svc-keytab HTTP/{{ hac_cntrl.name }}.{{ ald.domain }} --ktfile=/root/krb.keytab --pass-file=/root/pass-file

- name: сохранение keytab для передачи клиентам ald
  fetch: src=/root/krb.keytab dest=roles/ald_setup/files/krb.keytab validate_md5=yes flat=yes fail_on_missing=yes
