---
- hosts: ha_hosts
  user: root
  
  vars:
    corosync_conf: "/etc/corosync/"
    corosync_srv_conf: "/etc/default/corosync"
    cluster_ip: "192.168.50.55"
    
  tasks:
  
    - name: установка spkb-archive-keyring c предварительным обновлением кэша
      apt: pkg=$item update_cache=yes state=latest force=yes
      with_items:
        - spkb-archive-keyring
        
    - name: установка pacemaker c предварительным обновлением кэша
      apt: pkg=$item update_cache=yes state=latest force=yes
      with_items:
        - pacemaker
        - pacemaker-mgmt
        - corosync
        
    # ssh keys    
        
    - name: активация автозагрузки corosync
      lineinfile: dest=$corosync_srv_conf regexp=^START= line=START=yes
    
    - name: создание конфигурации сorosync
      copy: src=corosync.conf dest=$corosync_conf
      
    - name: перeзапуск corosync
      service: name=corosync state=restarted
      
    - name: выключание кворума
      command: crm configure property no-quorum-policy="ignore"
    - name: выключение fencing
      command: crm configure property stonith-enabled="false"
    
    - name: установка ip адреса кластера 
      command: crm configure primitive hacluster_ip ocf:heartbeat:IPaddr2 params ip=$cluster_ip iflabel="haip" op monitor interval="5"

    - name: reboot the servers
      command: /sbin/reboot -t now
