- hosts: virt_hosts
  user: root
    
  tasks:
  
    - name: убиванием процессы pacemaker и corosync
      command: killall -s 9 cib stonithd lrmd attrd pengine crmd mgmtd corosync
      ignore_errors: True
      
    - name: удаление pacemaker и сorosync
      apt: pkg=$item purge=yes state=absent
      with_items:
        - pacemaker-mgmt
        - pacemaker-mgmt-client
        - pacemaker
        - corosync
        
    - name: перезагружаем узлы
      command: /sbin/reboot -t now
         
