#
# © ОАО «Северное ПКБ», 2013
#
---
# script for make a VM and\or VM groups in ha cluster
- hosts: nodes
  user: root

  vars_files: ['../group_vars/all']

  vars:
    vms:
     - {config: '/home/artem/ha_cluster/mega-vm.xml', image: '/home/artem/ha_cluster/mega-vm.img'}
     - {config: '/home/artem/ha_cluster/mega2-vm.xml', image: '/home/artem/ha_cluster/mega2-vm.img'}


  tasks:
    #- name: получение имени ВМ из конфигурации
    #  local_action: command grep '<name>' ../../mega-vm.xml | sed -e 's/<name>//;s/<\/name>//'

    - debug: msg='Hello Wolrd!'
      when: inventory_hostname == common.master_node

    - debug: msg='{{ ip }}'
