#
# © ОАО «Северное ПКБ», 2013
#
---
# add new node in existed glusterfs volume
    - name: добавление узлов в glusterfs
      command: gluster peer probe {{ item }}
      with_items:
         groups.new_nodes
      when: inventory_hostname == common.master_node

    - name: добавление нового узла в том ${gluster.volume}
      command: gluster volume add-brick {{ gluster.volume }} {{ item }}:{{ gluster.placedir }}
      with_items:
         groups.new_nodes
      when: inventory_hostname == common.master_node

    - name: запуска ребалансировки тома ${gluster.volume}
      command: gluster volume rebalance {{ gluster.volume }} start
      when: inventory_hostname == common.master_node