#
# © ОАО «Северное ПКБ», 2013
#
---
# install glusterfs packages and restart service

    - name: установка glusterfs-server
      apt: pkg={{ item }} state=latest force=yes
      with_items: [glusterfs-server, attr]

    - name: настройка порта glusterfs
      lineinfile: dest=/etc/glusterfs/glusterd.vol
                  regexp="^#?.*option.*"
                  line="    option base-port 49216"
                  state=present
      when: extra_settings.custom_port

    - name: настройка каталога с конфигурацией для glusterfs
      lineinfile: dest=/etc/glusterfs/glusterd.vol
                  regexp="^.*option working-directory.*"
                  line="    option working-directory /etc/glusterd"
                  state=present
      when: extra_settings.custom_port

    - name: перезапуск службы glusterfs-server
      service: name=glusterfs-server state=restarted enabled=yes
      any_errors_fatal: true

    - name: создание папки под volume
      file: path={{ gluster.placedir }} state=directory

    - name: создание точки монтирования
      file: path={{ gluster.mount_point }} state=directory
      ignore_errors: true
