#
# © ОАО «Северное ПКБ», 2013
#
---
# setup main settings of glusterfs
    - name: добавление узлов в glusterfs
      command: gluster peer probe {{ item }}
      with_items: groups.nodes
      when: inventory_hostname == common.master_node
      any_errors_fatal: true

    - name: добавление узлов в glusterfs
      command: gluster peer probe {{ item }}
      with_items: groups.nodes
      when: inventory_hostname != common.master_node
      any_errors_fatal: true

    - name: создание тома
      command: gluster volume create {{ gluster.volume }} replica {{ groups['nodes']|length() }}
               transport tcp {{ groups['nodes']|join(":${gluster.placedir} ") }}:{{ gluster.placedir }}
               creates={{ extra_settings.path_to_config }}/glusterd/vols/{{ gluster.volume }}
      when: inventory_hostname == common.master_node
      any_errors_fatal: true

    - name: выключение NFS
      command: gluster volume set {{ gluster.volume }} nfs.disable on
      when: inventory_hostname == common.master_node and gluster.type_mount == 'glusterfs'
      ignore_errors: true

    - name: запуск тома
      command: gluster volume start {{ gluster.volume }}
               creates={{ extra_settings.path_to_config }}/glusterd/vols/{{ gluster.volume }}/run/{{ common.master_node }}-srv-vol.pid
      when: inventory_hostname == common.master_node
      ignore_errors: true
      any_errors_fatal: true
