#
# © ОАО «Северное ПКБ», 2013
#
---
# install glusterfs packages and restart service

    - name: установка glusterfs-server
      apt: pkg={{ item }} state=latest force=yes
      with_items: [glusterfs-server, attr]

    #- name: настройка glusterfs
    #  lineinfile: dest=/etc/glusterfs/glusterd.vol
    #              regexp="^#?.*option.*"
    #              line="    option base-port 49216"
    #              state=present

    - name: перезапуск службы glusterfs-server
      service: name=glusterfs-server state=restarted enabled=yes
