#
# © ОАО «Северное ПКБ», 2013
#
---
# setup main settings of glusterfs

    - name: добавление узлов в glusterfs
      command: gluster peer probe {{ item }}
      with_items:
         groups.nodes
      when: inventory_hostname == common.master_node

    - name: создание папки под volume
      file: path={{ gluster.placedir }} state=directory

    - name: создание тома
      command: gluster volume create {{ gluster.volume }} replica {{ groups['nodes']|length() }}
               transport tcp {{ groups['nodes']|join(":${gluster.placedir} ") }}:{{ gluster.placedir }}
               creates=/var/lib/glusterd/vols/{{ gluster.volume }}
               #creates=/etc/glusterd/vols/{{ gluster.volume }}
      when: inventory_hostname == common.master_node

    - name: выключение NFS
      command: gluster volume set {{ gluster.volume }} nfs.disable on
      when: inventory_hostname == common.master_node
      ignore_errors: True

    - name: запуск тома
      command: gluster volume start {{ gluster.volume }}
               creates=/var/lib/glusterd/vols/vm_storage_volume/run/{{ common.master_node }}-srv-vol.pid
               #creates=/etc/glusterd/vols/{{ gluster.volume }}/run/{{ common.master_node }}-srv.pid
      when: inventory_hostname == common.master_node
      ignore_errors: True
