#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: выключение fencing
      command: 'crm_attribute --attr-name stonith-enabled --attr-value false'
    
    - name: установка quorum-policy
      command: 'crm_attribute --attr-name no-quorum-policy --attr-value ignore'  
    #todo  
    #- name: установка схемы валидации с поддержкой fencing-topology
    #  command: " cibadmin -U -X '<cib validate-with="pacemaker-1.1"/>' "

    - name: копировать конфиг
      copy: src=temp.conf.xml dest=/tmp/temp.conf.xml 
       
    - name: подготовка секции resources из шаблона
      command: 'cibadmin --replace --scope resources --xml-file /tmp/temp.conf.xml'
    #todo  
    #- name: подготовка секции fencing-topology из шаблона
    #  command: 'cibadmin -M -c -o configuration --xml-text '<fencing-topology/>''
    
    - name: копировать конфиг
      copy: src=temp.const.xml dest=/tmp/temp.const.xml
      
    - name: подготовка секции constraints из шаблона
      command: 'cibadmin --replace --scope constraints --xml-file /tmp/temp.const.xml'
   
    - name: включение fencing
      command: 'crm_attribute --attr-name stonith-enabled --attr-value true'
    
    - name: установка quorum-policy
      command: 'crm_attribute --attr-name no-quorum-policy --attr-value stop'

