#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: выключение fencing
      command: crm_attribute --attr-name stonith-enabled --attr-value false
      
    - name: установка схемы валидации с поддержкой fencing-topology
      command: cibadmin -U -X '<cib validate-with="pacemaker-1.1"/>'
      
    - name: установка quorum-policy
      command: crm_attribute --attr-name no-quorum-policy --attr-value ignore

    #- name: подготовка секции resources из шаблона
    
    #- name: подготовка секции fencing-topology из шаблона
    
    #- name: подготовка секции constraints из шаблона
   
    #- name: выключение fencing
    #  command: crm_attribute --attr-name stonith-enabled --attr-value true
    
    - name: установка quorum-policy
      command: crm_attribute --attr-name no-quorum-policy --attr-value stop

