#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: очистка статусов узлов
      command: 'yes yes | crm node clearstate {{ item }}'
      with_items: groups.nodes

    - name: выключение fencing
      command: 'crm_attribute --attr-name stonith-enabled --attr-value false'
    
    - name: установка quorum-policy
      command: 'crm_attribute --attr-name no-quorum-policy --attr-value ignore'  
      
    - name: создание файла описания ресурсов(resources)
      template: src=resources.xml.j2 dest=/tmp/resources.xml

    - name: создание файла описания топологии(fencing topology)
      template: src=fencing_topology.xml.j2 dest=/tmp/fencing_topology.xml

    - name: создание файла описания ограничений(constraints)
      template: src=constraints.xml.j2 dest=/tmp/constraints.xml

    - name: копирование файла c командами сibadmin
      copy: src=pacemaker.sh dest=/tmp/pacemaker.sh mode=0775

    - name: инициализация кластера
      shell: pacemaker.sh chdir=/tmp




    


