#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: очистка статусов узлов
      command: 'crm -F node clearstate {{ item }}'
      with_items: groups.nodes
      ignore_errors: True

    - name: создание файла описания ресурсов(resources)
      template: src=resources.xml.j2 dest=/tmp/resources.xml

    - name: создание файла описания топологии(fencing topology)
      template: src=fencing_topology.xml.j2 dest=/tmp/fencing_topology.xml

    - name: создание файла описания ограничений(constraints)
      template: src=constraints.xml.j2 dest=/tmp/constraints.xml

    - name: установка правил валидации конфигурации кластера
      command: cibadmin -U -X '<cib validate-with="pacemaker-1.1"/>'

    - name: установка значения по-умолчанию свойства resource-stickiness для ресурсов
      command: crm_attribute --type rsc_defaults --attr-name resource-stickiness --attr-value 500

    - name: установка значения по-умолчанию timeout операций для ресурсов
      command: crm_attribute --type op_defaults --attr-name timeout --attr-value 130s

    - name: копирование файла c командами сibadmin
      copy: src=pacemaker.sh dest=/tmp/pacemaker.sh mode=0775

    - name: инициализация кластера
      command: /tmp/pacemaker.sh

    - name: ожидание создания ресурсов КВГ
      local_action: pause seconds=40 prompt="Wait please......."

