#
# © ОАО «Северное ПКБ», 2013
#
---
# setup pacemaker
  - include: setup_pacemaker_pkg.yml
  - include: configure_corosync.yml
  - include: configure_pacemaker.yml
    when: inventory_hostname == common.master_node
  - include: configure_acpi_option.yml
