#
# © ОАО «Северное ПКБ», 2014
#
---
# install pacemaker packages and restart service
    - name: Перед продолжением установки убедитесь, что ssh настроен на всех узлах (подробности в руководстве системного программиста)
      pause: prompt="press any key for continue or ctrl+c for cancel"

    - name: установка pacemaker
      apt: pkg=$item state=latest force=yes
      with_items: [pacemaker, corosync, fence-agents]
