 # specific network variables
network:
  control:
    address: '172.16.0'
    mask: '255.255.255.0'
    eth: [eth2, eth3]
    gateway:
    dns_search:
    dns_nameservers:

  public:
    address: '10.10.50'
    mask: '255.255.255.0'
    eth: [eth0, eth1]
    gateway:
    dns_search:
    dns_nameservers:

  bridge: 'br0'

hugepage:
   count: 10000
