#
# © ОАО «Северное ПКБ», 2013
#
---
# setup&configure hac_cntrl
    - name: установка пакетов для ПК Управления КВГ
      apt: pkg={{ item }} update_cache=yes state=latest force=yes
      with_items:
         - firefox
         - python-django
         - python-setuptools
         - apache2
         - libapache2-mod-wsgi
         - libapache2-mod-auth-kerb
         - pacemaker-mgmt
         - python-netsnmp
         - ipmitool
         - hac-control-apache

    - name: настройка конфигурационных файлов ПК Управления
      template: src={{ item }}.j2 dest=/etc/hac-control/{{ item }}
      with_items: ['hac.conf','infrastructure.conf','virt_install_cmd','policy.conf']

    - name: создание каталога для файлового кэша ПК управления
      file: path={{ gluster.mount_point }}/hac-control-cache state=directory mode=0777

    - name: настройка конфигурационных файлов apache2 для ПК Управления
      template: src=hac-control.j2 dest=/etc/apache2/sites-available/hac-control

    - name: остановка и отключение автозапуска служб apache2
      service: name=apache2 state=stopped enabled=no

