#
# © ОАО «Северное ПКБ», 2014
#
---
# remove node from cluster
   - command: 'crm -F node delete {{ item }}'
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: остановка ipmi ресурсов
     command: 'crm -F resource stop stonith_{{ item }}'
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: ожидание остановки ipmi ресурсов
     pause: seconds=60

   - name: удаление ipmi ресурсов
     command: 'crm -F configure delete stonith_{{ item }}'
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: остановка fenceapc ресурсов
     command: 'crm -F resource stop fence_{{ item.0 }}_{{ item.1 }}_{{ item.2 }}'
     with_nested:
        - groups.remove_nodes
        - pdu.keys()
        - ['on', 'off']
     ignore_errors: yes
     
   - name: ожидание остановки fenceapc ресурсов
     pause: seconds=60  

   - name: удаление fenceapc ресурсов
     command: 'crm -F configure delete fence_{{ item.0 }}_{{ item.1 }}_{{ item.2 }}'
     with_nested:
        - groups.remove_nodes
        - pdu.keys()
        - ['on', 'off']
     ignore_errors: yes

   - name: удаление fence_topology
     shell: cibadmin --delete --xml-text '<fencing-level target="{{ item }}"/>' && cibadmin --delete --xml-text '<fencing-level target="{{ item }}"/>' 
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: Удаление brick из glusterfs на удаляемых узлах
     shell: 'yes | gluster volume remove-brick {{ gluster.volume }} {{ item }}:{{ gluster.placedir }}'
     with_items: groups.remove_nodes
     any_errors_fatal: true

   - name: Удаление узлов из glusterfs
     command: gluster peer detach {{ item }}
     with_items: groups.remove_nodes
     any_errors_fatal: true
