#
# © ОАО «Северное ПКБ», 2014
#
---
# remove node from cluster
    - name: Переводим удалямые узлы в standby режим
      command: crm_standby -v true

    - name: ожидание выполнения операции перевода в standby
      pause: seconds=60

    - name: Останавливаем corosync на удаляемых узлах
      service: name=corosync enabled=no

    - name: Останавливаем работающие сервисы corosync и pacemaker
      command: killall -s 9 {{ item }}
      with_items: [cib, stonithd, lrmd, attrd, pengine, crmd, mgmtd, corosync]
      ignore_errors: true

  #  - name: Удаляем пакеты с ПО ВГ
  #    apt: pkg={{ item }} state=absent force=yes purge=yes
  #    with_items: [pacemaker-mgmt, pacemaker-mgmt-client, pacemaker, corosync]

  #  - name: удаление базы cib
  #    command: rm -rf /var/lib/heartbeat



