#
# © ОАО «Северное ПКБ», 2014
#
---
# remove node from cluster
    - name: переводим удалямые узлы в standby режим
      command: crm_standby -v true

    - name: ожидание выполнения операции перевода в standby
      pause: seconds=60

    - name: исключение corosync на удаляемых узлах из автозагрузки
      service: name=corosync enabled=no state=stopped

