#
# © ОАО «Северное ПКБ», 2013
#
---
# add new node(s) to cluster
- hosts: new_nodes
  user: root
  roles:
   - initial_settings

- hosts: new_nodes
  user: root
  tasks:
   - include: roles/glusterfs/tasks/setup_glusterfs_pkg.yml

- hosts: nodes
  user: root
  roles:
   - add_node_glusterfs

- hosts: new_nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml']
  roles:
   - libvirt
   - {role: hac_cntrl, network.control.address: $from_main, network.bridge: $from_main }

- hosts: new_nodes
  user: root
  roles:
   - pacemaker

- hosts: nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml']
  roles:
   - { role: add_node_pacemaker, network.control.address: $from_main }

