#
# © ОАО «Северное ПКБ», 2013
#
---
# add new node(s) to cluster
- hosts: new_nodes
  user: root
  roles:
   - initial_settings

- hosts: new_nodes
  user: root
  tasks:
   - include: roles/glusterfs/tasks/setup_glusterfs_pkg.yml

- hosts: nodes
  user: root
  roles:
   - { role: add_node }

- hosts: new_nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml']
  vars_prompt:
   - name: "my_password"
     prompt: "Enter password for ALD server administrator"
     private: yes
     confirm: yes
  roles:
   - libvirt
   - {role: hac_cntrl, network.control.address: $from_main, network.bridge: $from_main }
   - virtual_ald

# install pacemaker and just added node to cluster

