#
# © ОАО «Северное ПКБ», 2013
#
---
# add new node(s) to cluster
- hosts: new_nodes
  user: root
  roles:
   - initial_settings

- hosts: new_nodes
  user: root
  tasks:
   - include: roles/glusterfs/tasks/setup_glusterfs_pkg.yml

- hosts: nodes
  user: root
  vars_files: ['roles/glusterfs/vars/main.yml']
  roles:
   - { role: add_node, gluster.placedir: $from_main, gluster.volume: $from_main }

- hosts: new_nodes
  user: root
  vars_files: ['roles/glusterfs/vars/main.yml']
  tasks:
   - include: roles/glusterfs/tasks/mount.yml

# added libvirt
# install pacemaker and just added node to cluster
# install ald client
# install hac_cntrl
