#
# © ОАО «Северное ПКБ», 2014
#
---
- hosts: nodes
  user: root

  vars_prompt:
    - name: "ald_password"
      prompt: "Введите пароль для пользователя администратора ALD (admin/admin)"
      private: yes
      confirm: yes

    - name: "admin_password"
      prompt: "Введите пароль для пользователя администратора КВГ (${ald.kvg_admin_name})"
      private: yes
      confirm: yes

    - name: "user_password"
      prompt: "Введите пароль для пользователя оператора КВГ (${ald.operator_user})"
      private: yes
      confirm: yes

  roles:
    - ald_setup
