#
# © ОАО «Северное ПКБ», 2013
#
---
# for deploy cluster nodes
- hosts: nodes
  user: root
  roles:
   - initial_settings
#   - glusterfs
#   - libvirt
##   - пк управления
##   - ALD
##   - pacemaker + resources
