#
# © ОАО «Северное ПКБ», 2013
#
---
# for deploy cluster nodes
- hosts: nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml']
  roles:
   - initial_settings
   - glusterfs
   - libvirt
   - { role: hac_cntrl, network.control.address: $from_main, network.bridge: $from_main }
   - { role: pacemaker, network.control.address: $from_main }
   
- hosts: nodes
  user: root
  tasks:
    - name: создание каталога для ВМ (образы и файлы конфигурации)
      file: path={{ dirs.vm_images }} state=directory
      register: create_vm_images
      when: inventory_hostname == common.master_node
      ignore_errors: true

    - name: перемещение файлов /etc/libvirt/qemu на glusterfs
      command: cp -rf /etc/libvirt/qemu {{ dirs.vm_images }}
      when: create_vm_images.changed and inventory_hostname == common.master_node

    - name: удаление /etc/libvirt/qemu
      command: rm -rf /etc/libvirt/qemu
      when: create_vm_images.changed

    - name: делаем ссылку qemu в /etc/libvirt/
      file: src={{ dirs.vm_images }}/qemu dest=/etc/libvirt/qemu state=link
      when: create_vm_images.changed

