#
# © ОАО «Северное ПКБ», 2013
#
---
# for deploy cluster nodes
- hosts: nodes
  user: root

  vars_prompt:
  - name: "my_password"
    prompt: "Enter password for admin"
    private: yes
    confirm: yes
    default: "admin"

  roles:
#   - initial_settings
#   - glusterfs
#   - libvirt
#   - hac_cntrl
#   - ald_setup
##   - pacemaker + resources
