#
# © ОАО «Северное ПКБ», 2014
#
---
# Скрипт для создания репозитория ПК КВГ
- hosts: admin_stations
  user: root
#  connection: local
#  sudo: true
  vars: 
    ftp:
        # корневой каталог репозитория с пакетами Astra Linux SE 1.3 и ПК КВГ
        path_to_ftp_root: '/home/ftp'
        # имя каталога с пакетами Astra Linux SE 1.3
        astra_rep_name: 'astra'
        # имя каталога с пакетами devel Astra Linux SE 1.3
        dev_astra_rep_name: 'astra_dev'
        # имя каталога с пакетами ПК КВГ
        hac_rep_name: 'hac'
        # пусть к источнику пакетов Astra Linux SE 1.3 (обычно cd c Astra Linux)
        src_with_astra_rep: '/media/cdrom'
        # пусть к источнику пакетов для разработчика Astra Linux SE 1.3 devel
        src_with_dev_astra_rep: '/media/cdrom'
        # пусть к источнику пакетов ПК КВГ
        # полный путь до каталога содержащего пакеты ПК КВГ
        # указанный каталог должен содержать след. папки -> conf  db  dists  pool
        src_with_hac_rep: '/media/cdrom'

  roles:
   - repository

