#
# © ОАО «Северное ПКБ», 2013
#
---
# for deploy workstation for manage ha cluster
- hosts: admin_stations
  user: root
#  connection: local
#  sudo: True
  vars_files: ['roles/initial_settings/vars/main.yml']
  vars_prompt:
    - name: "ald_password"
      prompt: "Input ALD administrator password (admin/admin)"
      private: yes
      confirm: no

  pre_tasks:
    - include: roles/initial_settings/tasks/repo.yml

  roles:
   - { role: initial_workstation, tags: [init] }
   - { role: ald_client, tags: [ald] }
   - { role: users, tags: [ald, users] }
   - { role: firefox_vnc, tags: [vnc] }

  post_tasks:
    - name: удаление пакета haveged
      apt: pkg=haveged purge=yes state=absent

    - name: Для вступления в силу изменений компьютер(ы) будет перезагружен через 60 секунд...
      pause: prompt="press any key for continue or ctrl+c for cancel"  seconds=60

    - name: перезагружаем узлы
      command: /sbin/reboot -t now
      tags: [reboot]

