#
# © ОАО «Северное ПКБ», 2013-2014
#
---
# for deploy cluster nodes
- hosts: nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml']
  roles:
   - { role: initial_settings, tags: [init] }
   - { role: glusterfs, tags: [gluster] }
   - { role: libvirt, tags: [libvirt] }
   - { role: hac_cntrl, tags: [hac_cntrl] }

- hosts: nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml']
  vars_prompt:
    - name: "ald_password"
      prompt: "Input password ALD admin (admin/admin)"
      private: yes
      confirm: yes

    - name: "admin_password"
      prompt: "Input password HAC admin (kvg_admin)"
      private: yes
      confirm: yes

    - name: "user_password"
      prompt: "Input password HAC user (kvg_user)"
      private: yes
      confirm: yes

  pre_tasks:
   - name: отмонтирование glusterfs
     command: umount {{ gluster.mount_point }}
     ignore_errors: true
     tags: [ ald ]

   - name: перезапуск службы glusterfs-server
     service: name=glusterfs-server state=restarted
     tags: [ ald ]

   - name: ожидание перезапуска демон glusterfs
     pause: seconds=10
     tags: [ ald ]

   - name: монтирование glusterfs
     command: mount.glusterfs {{ common.master_node }}:/{{ gluster.volume }} {{ gluster.mount_point }}
     tags: [ ald ]

  roles:
   - { role: ald_setup, tags: [ ald, pure_ald ] }

  post_tasks:
   - name: ожидание остановки сервисов ald
     pause: seconds=10
     tags: [ ald, pure_ald ]

   - name: отмонтирование временно смонтированного ldap
     command: umount /var/lib/ldap
     ignore_errors: true

   - name: отмонтирование glusterfs
     command: umount {{ gluster.mount_point }}
     tags: [ ald ]

   - name: восстановление /etc/hosts
     template: src=roles/initial_settings/templates/hosts.j2 dest=/etc/hosts
     tags: [ ald, pure_ald ]

- hosts: nodes
  user: root
  vars_files: ['roles/initial_settings/vars/main.yml', 'roles/glusterfs/vars/main.yml']

  roles:
   - { role: pacemaker, tags: [ pacemaker ] }
   - { role: users, tags: [users] }

  post_tasks:
   - name: удаление пакета haveged
     apt: pkg=haveged purge=yes state=absent

