#
# © ОАО «Северное ПКБ», 2014
#
---
- hosts: remove_nodes
  user: root
  roles:
#   - remove_node

- hosts: nodes
  user: root
  tasks:
   - name: Удаление brick из glusterfs на удаляемых узлах
     command: bash -c 'yes | gluster volume remove-brick {{ gluster.volume }} {{ item }}:{{ gluster.placedir }}'
     with_items: groups.remove_nodes
     when: inventory_hostname == common.master_node
     ignore_errors: yes

   - name: Удаление узлов из glusterfs
     command: gluster peer detach {{ item }}
     with_items: groups.remove_nodes
     when: inventory_hostname == common.master_node
     ignore_errors: yes
