#
# © ОАО «Северное ПКБ», 2014
#
---
- hosts: nodes
  user: root
  tasks:
   - name: проверям если узлы в группе [remove_nodes] файла stage
     fail: msg="Not defined nodes in [remove_nodes] group in stage file!"
     when: groups['remove_nodes']|count == 0 and inventory_hostname == common.master_node
     any_errors_fatal: true
     tags: [remove_from_active_nodes]

- hosts: remove_nodes
  user: root
  roles:
   - { role: remove_node, tags: remove_node }

- hosts: nodes
  user: root
  tasks:
   - include: roles/remove_node/tasks/active_nodes_ops.yml
     when: inventory_hostname == common.master_node
     tags: [remove_from_active_nodes]

- hosts: remove_nodes
  user: root
  roles:
   - { role: uninstall_cluster, tags: uninstall_node }
