#
# © ОАО «Северное ПКБ», 2014
#
---
- hosts: remove_nodes
  user: root
  roles:
   - remove_node

- hosts: nodes
  user: root
  tasks:
   - command: 'crm node delete {{ item }}'
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: удаление узлов из pacemaker
     command: 'crm_node --force -R {{ item }}'
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: удаление ipmi ресурсов
     command: bash -c 'yes | crm configure delete stonith_{{ item }}'
     with_items: groups.remove_nodes
     ignore_errors: yes

   - name: удаление fenceapc ресурсов
     command: bash -c 'yes | crm configure delete fence_{{ item.0 }}_{{ item.1 }}_on'
     with_nested:
        - groups.remove_nodes
        - pdu.keys()
     ignore_errors: yes
     
   - name: удаление fenceapc ресурсов
     command: bash -c 'yes | crm configure delete fence_{{ item.0 }}_{{ item.1 }}_off'
     with_nested:
        - groups.remove_nodes
        - pdu.keys()
     ignore_errors: yes   

   - name: Удаление brick из glusterfs на удаляемых узлах
     command: bash -c 'yes | gluster volume remove-brick {{ gluster.volume }} {{ item }}:{{ gluster.placedir }}'
     with_items: groups.remove_nodes
     when: inventory_hostname == common.master_node
     ignore_errors: yes

   - name: Удаление узлов из glusterfs
     command: gluster peer detach {{ item }}
     with_items: groups.remove_nodes
     when: inventory_hostname == common.master_node
     ignore_errors: yes

