#
# © ОАО «Северное ПКБ», 2014
#
---
- hosts: admin_stations
  user: root
  # connection: local
  # sudo: True
  vars_files: ['roles/initial_settings/vars/main.yml']

  tasks:
    - name: Перед выполнением деинсталляции убедитесь, что вы завершили сеансы пользователей ALD!
      pause: prompt="press any key for continue or ctrl+c for cancel"  seconds=30

    - name: закрываем процессы ALD
      shell: killall -s 9 {{ item }}
      with_items:
         - ${ald.services_list}
         - [firefox]
      ignore_errors: true

    - name: удаление пакетов
      apt: pkg={{ item }} state=absent purge=yes force=yes
      with_items: [glusterfs-client, glusterfs-common, ald-client, haproxy, ald-admin-common, nscd, nslcd]

    - name: очистка /etc/fstab
      mount: name={{ gluster.mount_point }}
             src={{ network.public.address }}.{{ hac_cntrl.ip }}:/{{ gluster.volume}}
             fstype={{ gluster.type_mount }}
             state=absent

    - name: admin_stations будут перезагружены через 60 секунд...
      pause: prompt="press any key for continue or ctrl+c for cancel"  seconds=60

    - name: перезагружаем ЭВМ администратора
      command: /sbin/reboot -t now
      tags: [reboot]

