#
# © ОАО «Северное ПКБ», 2013
#
---
# for deploy workstation for manage ha cluster
- hosts: admin_stations
  user: root
#  connection: local
#  sudo: True
  vars_files: ['roles/initial_settings/vars/main.yml']
  vars_prompt:
    - name: "ald_password"
      prompt: "Input ALD administrator password (admin/admin)"
      private: yes
      confirm: no

#  pre_tasks:
#    - include: roles/initial_settings/tasks/repo.yml

  roles:
   - { role: initial_workstation, tags: [init] }
   - { role: ald_client, tags: [ald] }
   - { role: users, tags: [ald] }
   - { role: firefox_vnc, tags: [vnc] }

  post_tasks:
    - name: Для вступления в сетевых настроек перезапустите службу networking или компьютер
      command: echo
