#
# © ОАО «Северное ПКБ», 2013
#
---
# for deploy workstation for manage ha cluster
- hosts: admin_stations
  user: root
  connection: local
#  sudo: True
  vars_files: ['roles/initial_settings/vars/main.yml']
  vars_prompt:
    - name: "ald_password"
      prompt: "Введите пароль администратора ALD (admin/admin)"
      private: yes
      confirm: no

#  pre_tasks:
#    - include: roles/initial_settings/tasks/repo.yml

  roles:
   - { role: initial_workstation, network.public.address: $from_main, network.public.mask: $from_main, network.control.address: $from_main , network.control.mask: $from_main }
   - ald_client
   - users
   - firefox_vnc

  post_tasks:
    - name: Для вступления в сетевых настроек перезапустите службу networking или компьютер
      command: echo
