#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: запрещаем запуск wicd-daemon
      service: name=wicd state=stopped enabled=no

    - name: запрещаем запуск avahi-daemon
      service: name=avahi-daemon state=stopped enabled=no

    - name: установка пакетов
      apt: pkg={{ item }} state=latest force=yes
      with_items: ['haveged', 'ntp']

    - name: установка пакетов для bonding
      apt: pkg={{ item }} state=latest force=yes
      with_items: ['ifenslave-2.6', 'bridge-utils']
      when: net.interfaces|count == 4

    - name: добавление модуля bonding в /etc/modules
      lineinfile: dest=/etc/modules regexp='.*bonding' line='bonding' state=present
      when: net.interfaces|count == 4

    - name: настройка interfaces для bonding
      template: src=interfaces_bonding.j2 dest=/etc/network/interfaces
      when: net.interfaces|count == 4

    - name: настройка interfaces для двуx адаптеров
      template: src=interfaces_double_eth.j2 dest=/etc/network/interfaces
      when: net.interfaces|count == 2

    - name: настройка interfaces для одного адаптера с dhcp (ДЛЯ ТЕСТОВ РАЗРАБОТЧИКА)
      template: src=interfaces_one_eth_dhcp.j2 dest=/etc/network/interfaces
      when: net.interfaces|count == 1 and net.dhcp

    - name: настройка interfaces для одного адаптера
      template: src=interfaces_one_eth.j2 dest=/etc/network/interfaces
      when: net.interfaces|count == 1 and not net.dhcp

    - name: настройка /etc/hosts
      template: src=hosts.j2 dest=/etc/hosts

    - name: создание точки монтирования
      file: path={{ gluster.mount_point }} state=directory
      ignore_errors: true

    - name: установка клиента glusterfs
      apt: pkg=glusterfs-client state=latest force=yes

    - name: монтирование glusterfs
      mount: name={{ gluster.mount_point }}
             src={{ network.public.address }}.{{ hac_cntrl.ip }}:/{{ gluster.volume}}
             fstype={{ gluster.type_mount }}
             opts='defaults,_netdev'
             dump=1
             state=mounted

    - name: настройка локального сервера времени
      template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes

    - name: удаление старого файла конфигурации
      command: rm /var/lib/ntp/ntp.conf.dhcp removes=/var/lib/ntp/ntp.conf.dhcp

    - name: запуск сервера времени
      service: name=ntp state=restarted enabled=yes

    - include: haproxy.yml
