#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: запрещаем запуск wicd-daemon
      service: name=wicd state=stopped enabled=no

    - name: настройка interfaces
      template: src=interfaces.j2 dest=/etc/network/interfaces
      register: interfaces

    - name: настройка /etc/hosts
      template: src=hosts.j2 dest=/etc/hosts

    - name: перезапуск узла
      command: /sbin/shutdown -r -t 3 now Rebooted by ansible
      when: interfaces.changed

    - name: ожидание остановки ssh соединения
      local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
      when: interfaces.changed

    - name: ожидание запуска ssh соединения
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=100
      when: interfaces.changed
     
    ## В текущей реализации ald сервера в ПК КВГ данная настройка не требуется  
    #- name: установка клиента glusterfs
    #  apt: pkg=glusterfs-client state=latest force=yes

    #- name: монтирование glusterfs
    #  mount: name='/ald_home'
    #         src={{ network.control.address }}.{{ nodes_ip[common.master_node] }}:/{{ gluster.volume}}
    #         fstype=glusterfs
    #         opts='defaults,_netdev'
    #         dump=1
    #         state=mounted  
