#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: запрещаем запуск wicd-daemon
      service: name=wicd state=stopped enabled=no

    - name: запрещаем запуск avahi-daemon
      service: name=avahi-daemon state=stopped enabled=no

    - name: установка пакетов
      apt: pkg={{ item }} state=latest force=yes
      with_items: ['ifenslave-2.6', 'bridge-utils', 'haveged']

   # - name: добавление модуля bonding в /etc/modules
   #   lineinfile: dest=/etc/modules regexp='.*bonding' line='bonding' state=present

   # - name: настройка interfaces
   #   template: src=interfaces.j2 dest=/etc/network/interfaces
   #   register: interfaces

    - name: настройка /etc/hosts
      template: src=hosts.j2 dest=/etc/hosts

    - name: создание точки монтирования
      file: path={{ gluster.mount_point }} state=directory
      ignore_errors: true

    - name: установка клиента glusterfs
      apt: pkg=glusterfs-client state=latest force=yes

    - name: монтирование glusterfs
      mount: name={{ gluster.mount_point }}
             src={{ network.public.address }}.{{ hac_cntrl.ip }}:/{{ gluster.volume}}
             fstype=glusterfs
             opts='defaults,_netdev'
             dump=1
             state=mounted

    - name: настройка локального сервера времени
      template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes

    - name: запуск сервера времени
      service: name=ntp state=started enabled=yes
