#
# © ОАО «Северное ПКБ», 2014
#
---
- name: установка пакетов для сервера ALD
  apt: pkg=$item state=latest
  with_items:
    - ald-admin
    - ald-client
    - ald-client-common
    - smolensk-security-ald
  tags: [ packages ]
                     
- name: создание файла настройки пользователей
  template: src=pass-file.j2 dest=/root/pass-file mode=0600
  tags: [ pass-file ]
  
#- name: удаление /ald_home
#  command: rm -rf /ald_home  
  
#- name: подмена каталога /ald_home
#  file: src={{ dirs.ald_env_users }} dest=/ald_home state=link
  
- name: размонтирование /ald_home
  command: umount /ald_home
  ignore_errors: true

- name: удаление старых keytab
  command: rm -rf /etc/krb5.keytab
  ignore_errors: yes  

- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ]

- name: замена стандартных шаблонов ALD
  template: src={{ item }} dest=/etc/ald/config-templates/{{ item }}
  with_items:
    - krb5.conf
  tags: [ config ]

- name: настройка клиента ALD
  command: ald-client commit-config -f --pass-file=/root/pass-file 

- name: подмена каталога /ald_home
  mount: name=/ald_home src={{ dirs.ald_env_users }}
         fstype=none opts=bind,_netdev state=mounted
