#
# © ОАО «Северное ПКБ», 2014
#
---        

- name: создание групп пользователей
  ald: task=group group={{ item }} pass_file=/root/pass-file
  with_items: ald.groups  

- name: создание учетной записи администратора в ALD
  command: ald-admin user-add -f --pass-file=/root/pass-file --create-home --group={{ ald.groups[0] }} --full-name='Администратор' --user-desc='Администратор КВГ' {{ ald.kvg_admin_name }}
  
- name: создание учетной записи оператора в ALD
  command: ald-admin user-add -f --pass-file=/root/pass-file --create-home --group={{ ald.groups[1] }} --full-name='Оператор' --user-desc='Оператор КВГ' {{ ald.operator_user }}
  
#- name: Добавление пользователя в группу administrators
#  command: ald-admin group-mod {{ item }} -f --pass-file=/root/pass-file --add-users --user={{ ald.kvg_admin_name }} 
#  with_items: ald.groups
#  when: inventory_hostname == ald.master_ald_srv
  
- name: добавление привилегий для администратора
  command: ald-admin user-ald-cap {{ ald.kvg_admin_name }} -f --pass-file=/root/pass-file --c-admin=1 --c-all-hosts-add=1 --c-adm-user=1  
 
