#
# © ОАО «Северное ПКБ», 2014
#
---        

- name: создание групп пользователей
  ald: task=group group={{ item.1.group }} pass_file=/root/pass-file
  with_items: ald.users|dictsort

- name: создание учетной записи администратора в ALD
  ald: task=user pass_file=/root/pass-file group={{ ald.users.admin.group }}
       full_name='Administrator' user_desc='Administrator HAC' user={{ ald.users.admin.login }}
  register: create_users

- name: создание учетной записи оператора в ALD
  ald: task=user pass_file=/root/pass-file group={{ ald.users.user.group }}
       full_name='User' user_desc='User HAC' user={{ ald.users.user.login }}

- name: ожидание создания пользователей
  pause: seconds=60 prompt="wait please..."
  when: create_users.changed

- name: добавление привилегий для администратора
  command: ald-admin user-ald-cap {{ ald.users.admin.login }} -f --pass-file=/root/pass-file --c-admin=1 --c-all-hosts-add=1 --c-adm-user=1

