#
# © ОАО «Северное ПКБ», 2014
#
---
  - name: создание каталога ключей администраторов
    file: path=$admin_home/.ssh
          state=directory mode=0755

  - name: создание SSH ключей для администраторов
    command: ssh-keygen -q -t rsa -N '' -f $admin_home/.ssh/id_rsa
             creates=$admin_home/.ssh/id_rsa

  - name: извлечение публичного ключа
    fetch: src=$admin_home/.ssh/id_rsa.pub dest=roles/users/files/id_rsa.pub flat=yes fail_on_missing=yes
