#
# © ОАО «Северное ПКБ», 2014
#
---
#- include: ald.yml tags=users
#  when: inventory_hostname == common.master_node

#- name: настройка доступа пользователей
#  command: ald-admin user-ald-cap {{ ald.kvg_admin_name }} -f --pass-file=/root/pass-file --add-hosts --host={{ item }}.{{ ald.domain }}
#  with_items: groups.nodes
#  tags: users
#  when: inventory_hostname == common.master_node

#- name: настройка доступа пользователей
#  command: ald-admin user-ald-cap {{ ald.operator_user }} -f --pass-file=/root/pass-file --add-hosts --host={{ item }}.{{ ald.domain }}
#  with_items: groups.nodes
#  tags: users
#  when: inventory_hostname == common.master_node

- include: key.yml tags=users
  when: inventory_hostname == common.master_node

- include: sudo.yml tags=users
  when: inventory_hostname in groups.nodes

- name: копирование ключа на узел администрирования
  copy: src=id_rsa.pub dest=/root/.ssh/admin.pub mode=0600 owner=${ald.kvg_admin_name} group=${ald.groups[0]}
  when: inventory_hostname in groups.admin_stations

- name: добавление ключа в список авторизованных
  shell: cat /root/.ssh/admin.pub >> /root/.ssh/authorized_keys
  when: inventory_hostname in groups.admin_stations

- name: удаление файла ключа
  file: path=/root/.ssh/admin.pub state=absent
  when: inventory_hostname in groups.admin_stations

- name: установка прав на ключи
  file: path=/ald_home/${ald.kvg_admin_name}/.ssh
        owner=${ald.kvg_admin_name} group=${ald.groups[0]}
        state=directory recurse=yes
  when: inventory_hostname in groups.admin_stations
