#
# © ОАО «Северное ПКБ», 2013
#
---
# make a initial settings on nodes
    - include: repo.yml
    - include: limits.yml
#    - include: hugepage.yml
#    - include: network.yml
#    - include: ssh.yml
