#
# © ОАО «Северное ПКБ», 2014
#
---
   - name: остановка сервер времени
     service: name=ntp state=stopped enabled=no

   - name: установка в cron задачи по синхронизации времени по сети управления
     cron:
        name="sync time with admin's computer (control network)"
        special_time=hourly
        job="ntpdate {{ network.control.address }}.{{ ntp.ip_server }} 1>/dev/null && ntpdate {{ network.control.address }}.{{ ntp.ip_server }} 1>/dev/null"

   - name: установка в cron задачи по синхронизации времени по сети данных
     cron:
        name="sync time with admin's computer (public network)"
        special_time=daily
        job="ntpdate {{ network.public.address }}.{{ ntp.ip_server }} 1>/dev/null && ntpdate {{ network.public.address }}.{{ ntp.ip_server }} 1>/dev/null"

