#
# © ОАО «Северное ПКБ», 2014
#
---
   - name: остановка сервера времени
     service: name=ntp state=stopped enabled=no

   - name: установка в cron задачи по синхронизации времени по сети управления
     cron:
        name="sync time with admin's computer (control network)"
        special_time=hourly
        job="/usr/sbin/ntpdate {{ network.control.address }}.{{ ntp.ip_server }} 1>/dev/null && /usr/sbin/ntpdate {{ network.control.address }}.{{ ntp.ip_server }} 1>/dev/null"

   - name: установка в cron задачи по синхронизации времени по сети данных
     cron:
        name="sync time with admin's computer (public network)"
        special_time=daily
        job="/usr/sbin/ntpdate {{ network.public.address }}.{{ ntp.ip_server }} 1>/dev/null && /usr/sbin/ntpdate {{ network.public.address }}.{{ ntp.ip_server }} 1>/dev/null"

