#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: создание каталога ssh ключей root
      file: path=/root/.ssh state=directory mode=0755

    - name: создание SSH ключей для root
      command: ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
               creates=/root/.ssh/id_rsa

    - name: извлечение публичного ключа
      fetch: src=/root/.ssh/id_rsa.pub dest=roles/initial_settings/files/id_rsa_{{ inventory_hostname }}.pub flat=yes fail_on_missing=yes

    - name: копирование ключей на узлы
      copy: src=roles/initial_settings/files/id_rsa_{{ item }}.pub dest=/root owner=root group=root mode=0644
      with_items: groups.nodes

    - name: добавление ключа в список авторизованных
      shell: cat /root/id_rsa_{{ item }}.pub >> /root/.ssh/authorized_keys
      with_items: groups.nodes

    - name: очистка временных файлов
      command: rm /root/id_rsa_{{ item }}.pub
      with_items: groups.nodes

    - name: настройка ssh
      lineinfile: dest=/etc/ssh/ssh_config
                  regexp="^#?.*BatchMode.*"
                  line="    BatchMode yes"
                  state=present

    - name: настройка ssh
      lineinfile: dest=/etc/ssh/ssh_config
                  regexp="^#?.*StrictHostKeyChecking.*"
                  line="    StrictHostKeyChecking no"
                  state=present
