---
- hosts: ha_hosts
  user: root
  
  vars_files:
    - ../vars/vars_gluster.yml

  vars:
    is_master: "'$inventory_hostname' == '${gluster.master}'"
  
  tasks:
    - name: установка glusterfs-server c предварительным обновлением кэша
      apt: pkg=$item update_cache=yes state=latest
      with_items:
        - glusterfs-server
        
    - name: перезапуск службы glusterfs-server    
      service: name=glusterfs-server  state=restarted  enabled=yes
      tags:
         - start_and_mounting
         
    - name: создаем директории, где будет glusterfs (bricks)
      file: path=${gluster.place} state=directory
      
    - name: добавление узлов в кластер ${gluster.hosts}
      command: gluster peer probe $item
      with_items:
        ${gluster.hosts}
      when: is_master

    - name: создание тома ${gluster.volume}
      command: gluster volume create ${gluster.volume} replica ${gluster.count_hosts}
             transport tcp ${gluster.bricks}
             creates=/etc/glusterd/vols/${gluster.volume}
      when: is_master
      
    - name: запуск тома ${gluster.volume}
      command: gluster volume start ${gluster.volume} creates=${gluster.file_indicator} 
      when: is_master
      tags:
         - start_and_mounting
      
    - name: создание точки монтирования
      file: path=${gluster.mount} state=directory
      ignore_errors: True
      tags:
         - start_and_mounting
   
    - name: монтирование каталогов
      mount: name=${gluster.mount}
             src=${gluster.src_mount}
             fstype=glusterfs
             opts='defaults,_netdev'
             dump=1 state=mounted
      tags:
         - start_and_mounting

