#
# © ОАО «Северное ПКБ», 2014
#
---
- name: install ald packages for ALD client
  apt: pkg=$item state=latest
  with_items:
    - ald-client-common
    - ald-admin
    - ald-admin-parsec-mac
    
- name: установка модулей ALD для панели SMC
  apt: pkg=$item state=latest
  with_items:
      - smc-ald-audit
      - smc-ald-capabilities
      - smc-ald-device-ctrl
      - smc-ald-hosts
      - smc-ald-mac
      - smc-ald-policies
      - smc-ald-services
      - smc-ald-tasks
      - smc-ald-users
      - smolensk-security-ald
      - ald-client-fs
      - ald-admin-common
      - ald-admin-parsec-aud
      - ald-admin-parsec-devac
      - aldd
  tags: [ packages ]

- name: удаление старых keytab
  command: rm /etc/krb5.keytab
  ignore_errors: yes
  when: inventory_hostname in groups.admin_stations
  
- name: создание файла настройки пользователей
  template: src=pass-file.j2 dest=/root/pass-file mode=0600
  tags: [ pass-file ]
  when: inventory_hostname in groups.admin_stations
  
- name: создание файла настройки ALD (/etc/ald/ald.conf)
  template: src=ald.conf.j2 dest=/etc/ald/ald.conf
  register: ald_config
  tags: [ config ] 
  when: inventory_hostname in groups.admin_stations

- lineinfile: dest=/etc/ald/ald.conf
              regexp='^SERVER_ON='
              line='SERVER_ON=0'
  when: inventory_hostname in groups.admin_stations

- lineinfile: dest=/etc/ald/ald.conf
              regexp='^CLIENT_ON='
              line='CLIENT_ON=1'   
  when: inventory_hostname in groups.admin_stations

- ald: task=init_client pass_file=/root/pass-file

- name: Настройка доступа Администратора на клиентских станциях
  command: ald-admin user-ald-cap {{ ald.kvg_admin_name }} -f --pass-file=/root/pass-file --add-hosts --host={{ inventory_hostname }}.{{ ald.domain}}
  when: inventory_hostname  in groups.admin_stations
