#
# © ОАО «Северное ПКБ», 2014
#
---
# script for make a VM in ha cluster
  - name: проверка, что с ВМ указанным именем не запущена в КВГ
    command: crm resource status {{ item.name }}
    register: cmd_result
    failed_when: "'is running on' in cmd_result.stdout"
    any_errors_fatal: true
    with_items: vms

  - name: удаление ресурса из КВГ
    command: crm -F configure delete {{ item.name }}
    ignore_errors: true
    with_items: vms

  - name: удаление файлов с образом ВМ из КВГ (ПК РФС)
    file: path={{ dirs.vm_images }}/{{ item.name }}.img state=absent
    with_items: vms

  - name: удаление конфигурационных файлов ВМ из КВГ (ПК РФС)
    file: path={{ dirs.vm_images }}/qemu/{{ item.name }}.xml state=absent
    with_items: vms

  - name: копирование конфигурации ВМ
    copy: src={{ item.path }}{{ item.config }} dest={{ dirs.vm_images }}/qemu/{{ item.name }}.xml mode=0777
    with_items: vms

  - name: копирование образа ВМ
    copy: src={{ item.path }}{{ item.image }} dest={{ dirs.vm_images }}/{{ item.name }}.img mode=0777
    with_items: vms

  - name: создание ресурса VirtualDomain в КВГ
    command:  cibadmin -M -c -o resources --xml-text '<primitive id="{{ item.name }}" template="vm_template"><instance_attributes id="{{ item.name }}-instance_attributes"><nvpair id="{{ item.name }}-instance_attributes-config" name="config" value="{{ dirs.vm_images }}/qemu/{{ item.name }}.xml"/></instance_attributes></primitive>'
    with_items: vms

  ## устаревший вариант создания ВМ без шаблона  
  #- name: создание ресурса VirtualDomain в КВГ
  #  command: crm configure primitive {{ item.name }} ocf:heartbeat:VirtualDomain \
  #           meta allow-migrate="true" target-role="Stopped" \
  #           params hypervisor="qemu:///system" config="/etc/libvirt/qemu/{{ item.name }}.xml" migration_transport="tcp" \
  #           operations $id="{{ item.name }}-operations" \
  #           op monitor interval="10" timeout="30" \
  #           op migrate_from interval="0" timeout="90" \
  #           op migrate_to interval="0" timeout="90"
  #  with_items: vms
  #  when: inventory_hostname == common.master_node
