#
# © ОАО «Северное ПКБ», 2014
#
---
  - name: создание групп из VirtualDomain
    command: crm configure group {{ item.name }} {{ item.vm_list }}
             meta target-role="Started" is-managed="true" ordered="false" collocated="false"
    with_items: vm_groups
    when: inventory_hostname == common.master_node and vm_groups is defined
